config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'registrations' }

  root to: 'posts#index'
  resources :posts
  get 'users/profile'
  patch 'users/update' => 'users#update', as: 'user'
  get 'toggle_grade/:grade' => 'grades#toggle_grade', as: 'toggle_grade'
  get 'toggle_bookmark/:post' => 'bookmarks#toggle_bookmark', as: 'toggle_bookmark'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  attr_accessor :std
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/


  validates_presence_of :type


  validates_presence_of :std , allow_blank: false , if: -> { type == 'Student' and new_record? },
                         message: 'Student must add grade to continue'



  scope :admins, -> { where(type: 'Admin') }
  scope :teachers, -> { where(type: 'Teacher') }
  scope :students, -> { where(type: 'Student') }
  scope :guardians, -> { where(type: 'Guardian') }

  has_many :posts, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  def get_grade_posts(cls)
    post = []
    Grade.where(cls: cls).each do |g|
      unless g.posts.empty?
        post << g.posts
      end
    end
    post
  end

  def user_all_grade_posts # for teachers,admins,guardians
    user_grades = self.grades.pluck(:cls)
    all_user_grades_posts = Hash.new{|h,k| h[k] = [] }

    user_grades.each do |grade|
      post = get_grade_posts(grade)
      all_user_grades_posts[grade].push(post)
    end
    all_user_grades_posts
  end


  def grade_status(grade)
    if self.grades.pluck(:cls).include? grade.to_i
      return 'Delete grade'
    end
    'Add grade'
  end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def profile
    @grade_list = %w[1 2 3 4 5 6 7 8 9 10 11 12]

  end

  def update
    role = current_user.type.downcase.to_sym
    current_user.update(

        email: params[role][:email],
        avatar: params[role][:avatar]
    )
    redirect_to action: 'profile'

  end

end

app/views/users/_student_profile.html.erb
<main>
  <h1>Profile</h1>
  <h4>Role: <%= current_user.type %></h4>

  <div>
    <%= image_tag current_user.avatar.url(:medium) %>
  </div>

  <%= form_for current_user, url: user_path(current_user), html: {method: :patch} do |f| %>

    <div class="form-field">

      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>

    <div class="form-field">
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
    </div>

    <div class="form-field">
      <%= f.submit "Update Profile" %>
    </div>

  <% end %>
</main>

app/views/users/_teacher_profile.html.erb
<main>
  <h1>Profile</h1>
  <h4>Role: <%= current_user.roles[0].name %></h4>

  <div>
    <%= image_tag current_user.avatar.url(:medium) %>
  </div>

  <%= form_for current_user, url: user_path(current_user), html: { method: :patch } do |f| %>

    <div class="form-field">

      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>

    <div class="form-field">
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
    </div>

    <div class="form-field">
      <%= f.submit "Update Profile" %>
    </div>

  <% end %>

  <% @grade_list.each do |grade| %>
    <h4><%= grade %></h4>
    <% if current_user.grades.pluck(:cls).include? grade.to_i %>
      <%= link_to 'Delete grade', remove_grade_path(grade), method: :delete %>
    <% else %>
      <%= link_to 'Add grade', add_grade_path(grade), method: :post %>
    <% end %>
  <% end %>

  <%= link_to 'Back', posts_path %>

</main>

app/views/users/profile.html.erb
<main>
  <% if current_user.type == 'Teacher' %>
    <%= render 'users/teacher_profile' , grade_list: @grade_list  %>
  <% elsif current_user.type == 'Student' %>
    <%= render 'users/student_profile' %>
  <% end %>

</main>