config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'registrations' }

  root to: 'posts#index'
  resources :posts
  get 'users/profile'
  patch 'users/update' => 'users#update', as: 'user'
  get 'toggle_grade/:grade' => 'grades#toggle_grade', as: 'toggle_grade'
  get 'toggle_bookmark/:post' => 'bookmarks#toggle_bookmark', as: 'toggle_bookmark'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  # resourcify

  belongs_to :teacher, optional: true, class_name: 'Teacher', foreign_key: 'user_id'
  belongs_to :admin, optional: true, class_name: 'Admin', foreign_key: 'user_id'
  belongs_to :user, optional: true

  # a post can only be in single grade
  belongs_to :grade, optional: true

  belongs_to :bookmark, optional: true

  def bookmark_status(user)
    user.bookmarks.each do |bookmark|
      if bookmark.post_id == self.id
        return 'Remove as bookmark'
      end
    end
    'Add as bookmark'

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:edit, :update, :destroy]
  # load_and_authorize_resource


  def index

  end

  def new
    @post = Post.new
  end

  def create
    grade = current_user.grades.find_by(cls: params[:post][:grade].to_i)

    @post = Post.create(
        title: params[:post][:title],
        content: params[:post][:content],
        user_id: current_user.id,
        grade_id: grade.id
    )

    redirect_to action: 'index'


  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post.update(post_params)
    redirect_to action: 'index'

  end

  def destroy
    @post.destroy
    redirect_to action: 'index'
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title,:content)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for post do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :post_content %>
  </div>
  <input type="hidden" name="post[grade]" value="<%= grade %>">

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_student_index.html.erb
<div style="display: flex">
  <div class="left-sidebar"
       style="display: flex;
           width: 20%;
           flex-direction: column;">
    <h4 class="bookmark_posts">click me to Show Bookmarked Posts</h4>
    <h4 class="grade_posts" id="">click me Grade Posts</h4>
  </div>

  <div class="right-sidebar" style="display: inline-block;text-align: center;width: 40%;">
    <div class="student_grade_posts">
      <h1>Grade:<%= current_user.grade.cls %>  Posts</h1>
      <% current_user.student_grade_posts.each do |post| %>
        <% post.each do |p| %>
          <div class="post-content"
               style="width: 320px;
                   margin: 0 auto;
                   padding: 15px;
                   border: 1px solid #CCC;
                   border-radius: 1em;">
            <p>Title:  <%= p.title %></p>
            <p>Content:  <%= p.content %></p>
            <%= link_to p.bookmark_status(current_user), toggle_bookmark_path(post: p) %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="student_bookmarked_posts" style="display: none;">
      <h1>Bookmarked Posts</h1>
      <% current_user.student_bookmarked_posts.each do |post| %>
          <div class="post-content"
               style="width: 320px;
                   margin: 0 auto;
                   padding: 15px;
                   border: 1px solid #CCC;
                   border-radius: 1em;">
            <p>Title:  <%= post.title %></p>
            <p>Content:  <%= post.content %></p>
            <%= link_to post.bookmark_status(current_user), toggle_bookmark_path(post: post) %>
          </div>
      <% end %>

    </div>
  </div>
</div>

<script>
  $(document).ready(function () {
      var ele1 = $('.student_grade_posts');
      var ele2 = $('.student_bookmarked_posts');
      $('.bookmark_posts').click(function () {
          ele1.hide();
          ele2.show();
      });
      $('.grade_posts').click(function () {
          ele1.show();
          ele2.hide();
      });

  });



</script>

app/views/posts/_teacher_index.html.erb
<div style="display: flex">
  <div class="left-sidebar"
       style="display: flex;
           width: 10%;
           flex-direction: column;">
    <h1>Grades</h1>
    <ul style="font-size: 24px">
      <% current_user.grades.pluck(:cls).each do |c| %>
        <li class="grade-cls" style="cursor: pointer"><%= c %></li>
      <% end %>
    </ul>

  </div>

  <div class="right-sidebar" style="display: inline-block;text-align: center;width: 40%;">
    <h1>Posts</h1>
    <% current_user.user_all_grade_posts.each do |grade, posts| %>
      <div id="grade-<%= grade %>" class="grade-content" style="display: none">
        <% posts.each do |post| %>
          <% post.each do |pst| %>
            <% pst.each do |p| %>
              <div class="post-content"
                   style="width: 320px;
                       margin: 0 auto;
                       padding: 15px;
                       border: 1px solid #CCC;
                       border-radius: 1em;">
                <p>Title:  <%= p.title %></p>
                <p>Content:  <%= p.content %></p>
                <p>Grade: <%= grade %></p>
                <% if current_user == p.user %>
                  <%= link_to 'Delete', post_path(p.id), method: :delete %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        <% end %>
        <%= link_to 'New Post', new_post_path(grade: grade) %>
      </div>
    <% end %>

  </div>
</div>

<script>

    $(document).ready(function () {

        $('.grade-cls').click(function () {
            $('.grade-content').hide();
            var val = $(this).html();
            $('#grade-' + val).show();

        });


    });


</script>



<!--<table>-->
<!--  <thead>-->
<!--  <tr>-->
<!--    <th>Title</th>-->
<!--    <th>Content</th>-->
<!--    <th>User Role</th>-->
<!--    <th colspan="3"></th>-->
<!--  </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
<%# @posts.each do |post| %>
<!--    <tr>-->
<%# if @ability.can? :read, post %>
<!--        <td><%#= post.title %></td>-->
<!--        <td><%#= post.content %></td>-->
<!--        <td><%#= post.user.roles.pluck(:name)[0] %></td>-->
<%# end %>

<!--      <td><%#= link_to 'Show', post %></td>-->
<%# if @ability.can? :update, post,user_id: current_user.id %>
<!--        <td><%#= link_to 'Edit', edit_post_path(post) %></td>-->
<%# end %>

<%# if @ability.can? :destroy, post, user_id: current_user.id %>
<!--        <td><%#= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<%# end %>
<!--    </tr>-->
<%# end %>
<!--  </tbody>-->
<!--</table>-->

<br>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<main>
  <% if current_user.type == 'Teacher' %>
    <%= render 'posts/teacher_index'  %>
  <% end %>
  <% if current_user.type == 'Student' %>
    <%= render 'posts/student_index' %>
  <% end %>

</main>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post, grade: params[:grade] %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>
<p>
  created by <%= @post.user.email %>
  role <%= current_user.roles.pluck(:name)[0] %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>