config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'registrations' }

  root to: 'posts#index'
  resources :posts
  get 'users/profile'
  patch 'users/update' => 'users#update', as: 'user'
  get 'toggle_grade/:grade' => 'grades#toggle_grade', as: 'toggle_grade'
  get 'toggle_bookmark/:post' => 'bookmarks#toggle_bookmark', as: 'toggle_bookmark'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>School</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%#= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> |
        <%= link_to 'Profile', users_profile_path, :class => 'navbar-link' %> |
        <%= current_user.type %>
      <% else %>
        <%= link_to 'Sign up', new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to 'Login', new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>